# Generated by Django 5.2.4 on 2025-07-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('institution', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('state_province', models.CharField(max_length=2)),
                ('degree', models.CharField(choices=[('Post-Doctoral Fellowship', 'Post-Doctoral Fellowship'), ('Ph.D.', 'Ph.D.'), ('Ed.D.', 'Ed.D.'), ('M.D.', 'M.D.'), ('J.D.', 'J.D.'), ('Doctorate', 'Doctorate'), ('M.F.A.', 'M.F.A.'), ('M.S.', 'M.S.'), ('M.Ed.', 'M.Ed.'), ('M.A.', 'M.A.'), ('M.B.A.', 'M.B.A.'), ("Master's", "Master's"), ('B.F.A.', 'B.F.A.'), ('B.S.', 'B.S.'), ('B.A.', 'B.A.'), ('B.B.A.', 'B.B.A.'), ("Bachelor's", "Bachelor's"), ('A.S.', 'A.S.'), ('A.A.', 'A.A.'), ("Associate's", "Associate's"), ('Certificate', 'Certificate'), ('Diploma', 'Diploma')], max_length=50)),
                ('field_of_study', models.CharField(max_length=255)),
                ('graduation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('employer', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('state_province', models.CharField(max_length=2)),
                ('remote', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='core_site.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('contract', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core_site.experience')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('show_after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_before', to='core_site.skillcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('show_after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_before', to='core_site.skill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='core_site.skillcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
