# Generated by Django 5.2.4 on 2025-08-14 03:52

from django.db import migrations, models


def load_initial_emails(apps, schema_editor):
    Email = apps.get_model('core_site', 'Email')
    Email.objects.create(event='contact form submission', subject='[Portfolio Inqury] {subject}', body='Name: {name}\nEmail: {email}\n\nMESSAGE:\n{message}')
    Email.objects.create(event='create portfolio item', subject='[Portfolio Notification] New {model_name} Created', body='Hello Ryan,\n\nA new {model_name} has been created in your portfolio. Details:\n{details}\n\nIf you created this item, no further action is necessary. Otherwise, please log into your porftolio, remove this item if it is not accurate, and change your password.')
    Email.objects.create(event='modify portfolio item', subject='[Portfolio Notification] {model_name} {id} Modified', body='<div><p>Hello Ryan,</p><br /><br /><p>{article_and_model} has been modified in your portfolio. Details:</p><br /><table><thead><tr><th>Property</th><th>Old</th><th>New</th><th>Changed</th></tr></thead><tbody>{details}</tbody></table><br /><br /><p>If you made these changes, no further action is necessary. Otherwise, please log into your portfolio, revert the changes, and change your password.</p>')
    Email.objects.create(event='delete portfolio item', subject='[Portfolio Notification] {model_name} {id} Deleted', body='Hello Ryan,\n\n{article_and_model} has been deleted in your portfolio. Details:\n{details}\n\nIf you deleted this item, no further action is necessary. Otherwise, please log into your portfolio, recreate the item, and change your password.')

def remove_initial_emails(apps, schema_editor):
    Email = apps.get_model('core_site', 'Email')
    Email.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='The event that triggers the email and the name of the email', max_length=255)),
                ('to', models.JSONField(blank=True, help_text='A list or tuple of email addresses, defaults to `(ryan@ryanmoscoe.com,)`', null=True)),
                ('from_email', models.EmailField(blank=True, help_text='Defaults to settings.DEFAULT_FROM_EMAIL', max_length=254, null=True)),
                ('reply_to', models.JSONField(blank=True, help_text='A list or tuple of email addresses, defaults to None', null=True)),
                ('subject', models.CharField(help_text='The Subject line for the email', max_length=255)),
                ('body', models.TextField(help_text='The email message body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.RunPython(load_initial_emails, remove_initial_emails)
    ]
