# Generated by Django 5.2.4 on 2025-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0002_email_alter_skillcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='invert_icon',
            field=models.BooleanField(default=False),
        ),
    ]
