# Generated by Django 5.2.4 on 2025-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0004_alter_accomplishment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
