# Generated by Django 5.2.4 on 2025-11-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_site', '0005_alter_skill_icon_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(blank=True, help_text='Option 1: enter a full email address', max_length=254, null=True)),
                ('domain', models.CharField(blank=True, help_text='Option 2: Enter only a domain to block all addresses on that domain', null=True)),
            ],
            options={
                'ordering': ['domain', 'address'],
            },
        ),
    ]
