# Generated by Django 5.2.4 on 2025-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_image_alt',
            field=models.CharField(default='default image alt text', max_length=512),
            preserve_default=False,
        ),
    ]
