# Generated by Django 5.2.4 on 2025-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_hero_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_credit_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_credit_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
