# Generated by Django 5.2.4 on 2025-08-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_site', '0002_email_alter_skillcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt', models.CharField(blank=True, max_length=150, null=True)),
                ('deployed_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('team', models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], default='Solo', max_length=10)),
                ('scope', models.CharField(blank=True, choices=[('FE', 'Front End'), ('BE', 'Back End'), ('FS', 'Full Stack'), (None, '')], max_length=20, null=True)),
                ('starter_code', models.BooleanField(blank=True, null=True)),
                ('prompt_engineering', models.BooleanField(default=False)),
                ('software_engineering', models.BooleanField(default=False)),
                ('elearning', models.BooleanField(default=False)),
                ('classroom', models.BooleanField(default=False)),
                ('show_after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_before', to='portfolio.project')),
                ('tech_stack', models.ManyToManyField(to='core_site.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('image_alt', models.CharField(max_length=150)),
                ('deployed_url', models.URLField()),
                ('show_after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_before', to='portfolio.coursematerial')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='portfolio.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
