# Generated by Django 5.2.4 on 2025-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.CharField(blank=True, choices=[('Front End', 'Front End'), ('Back End', 'Back End'), ('Full Stack', 'Full Stack'), (None, '')], max_length=20, null=True),
        ),
    ]
