# Generated by Django 5.2.4 on 2025-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_coursematerial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
